#!/bin/bash

set -e
set -o pipefail
VERSION='1.0'
basedir=$(dirname "$0")

AG=$(which ag)

if [ ! -x "$AG" ]; then
    echo "grep not found!"
    exit 2
fi

version () {
    echo "agaudit version: $VERSION"
}

usage() {
	cat <<EOF
Usage: agaudit [opts] /path/to/scan

OPTIONS
  -d <dbname> database to use or /path/to/file.db (uses default if not specified)

  -l lists databases available
  -v prints version number
  -h prints this help screen
EOF
}

listdb () {
    banner
if [ -n "$GRDIR" ] && [ -d "$GRDIR" ]; then
    ls -1 "$GRDIR/*.db"
fi
if [ -d /usr/share/graudit/ ]; then
     ls -1 /usr/share/graudit/*.db
fi
if [ -d ~/.graudit/ ]; then
     ls -1 ~/.graudit/*.db
fi
if [ -d "$basedir"/signatures/ ]; then
     ls -1 "$basedir"/signatures/*.db
fi
}

sigdb='default'

while getopts "d:hlv" opt; do
	case $opt in 
    d)
        sigdb="$OPTARG"
    ;;
	h) 
		usage
		exit 1
	;;
	l)
		listdb
		exit 0
	;;
	v)
	    version
	    exit 0
	;;
	\?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        exit 2
    ;;
	esac
done

if [ "$sigdb" == '-' ]; then
    database='-'
elif [ -f "$GRDIR/$sigdb.db"  ]; then
    database="$GRDIR/$sigdb.db"
elif [ -f "/usr/share/graudit/$sigdb.db" ]; then
    database="/usr/share/graudit/$sigdb.db"
elif [ -f "$HOME/.graudit/$sigdb.db" ]; then
    database="$HOME/.graudit/$sigdb.db"
elif [ -f "$basedir/signatures/$sigdb.db" ]; then
    database="$basedir/signatures/$sigdb.db"
else
    database="$sigdb"
fi

if [ "$sigdb" == "c" ]; then
	sigdb="cc"
fi

shift $((OPTIND-1))

if [ -z "$1" ]; then
        usage
        exit 2
fi

# ag --color-match --java "($(paste -sd "|" signatures/java.db))" t/example.jsp  | head
$AG \
	--color-match \
	--$sigdb \
	"($(paste -sd "|" $database))" \
	"$@"

SUCCESS=$?
exit $SUCCESS
