#!/bin/bash

set -e
set -o pipefail
VERSION='1.0'
basedir=$(dirname "$0")

AG=$(which ag)

context="1"
nocolor=""
vimlines=""

if [ ! -x "$AG" ]; then
    echo "ag not found!"
    exit 2
fi

version () {
    echo "agaudit version: $VERSION"
}

usage() {
	cat <<EOF
Usage: agaudit [opts] /path/to/scan

OPTIONS
  -c <num>    number of lines for context (default = 1)
  -d <dbname> database to use or /path/to/file.db (uses default if not specified)
  -L vim friendly lines
  -Z high contrast colors
  -z supress colors

  -l lists databases available
  -v prints version number
  -h prints this help screen
EOF
}

listdb () {
if [ -n "$GRDIR" ] && [ -d "$GRDIR" ]; then
    ls -1 "$GRDIR/*.db"
fi
if [ -d /usr/share/graudit/ ]; then
     ls -1 /usr/share/graudit/*.db
fi
if [ -d ~/.graudit/ ]; then
     ls -1 ~/.graudit/*.db
fi
if [ -d "$basedir"/signatures/ ]; then
     ls -1 "$basedir"/signatures/*.db
fi
}

sigdb='default'

while getopts "c:d:hLlvZz" opt; do
	case $opt in 
    	c)
		context="$OPTARG"
	;;
    	d)
        	sigdb="$OPTARG"
    	;;
	h) 
		usage
		exit 1
	;;
	L)
		vimlines="--vimgrep"
	;;
	l)
		listdb
		exit 0
	;;
	v)
	    	version
	    	exit 0
	;;
	Z)
		nocolor="--color"
	;;
	z)
		nocolor="--nocolor"
	;;
	\?)
        echo "Invalid option: -$OPTARG" >&2
        usage
        exit 2
    ;;
	esac
done

if [ "$sigdb" == '-' ]; then
    database='-'
elif [ -f "$GRDIR/$sigdb.db"  ]; then
    database="$GRDIR/$sigdb.db"
elif [ -f "/usr/share/graudit/$sigdb.db" ]; then
    database="/usr/share/graudit/$sigdb.db"
elif [ -f "$HOME/.graudit/$sigdb.db" ]; then
    database="$HOME/.graudit/$sigdb.db"
elif [ -f "$basedir/signatures/$sigdb.db" ]; then
    database="$basedir/signatures/$sigdb.db"
else
    database="$sigdb"
fi

case $sigdb in
	c)
		sigdb="cc"
		;;
	dotnet)
		sigdb="cs"
		;;
esac

shift $((OPTIND-1))

if [ -z "$1" ]; then
        usage
        exit 2
fi

$AG \
	-C $context \
	--$sigdb \
	$nocolor \
	$vimlines \
	"($(grep -v ^\# $database | paste -sd "|"))" \
	"$@"

SUCCESS=$?
exit $SUCCESS
